// Generated by CoffeeScript 1.10.0
(function() {
  var Identified, d, pjson, ref;

  ref = require('lightsaber/lib/log'), pjson = ref.pjson, d = ref.d;

  Identified = (function() {
    var randomKey;

    function Identified() {}

    Identified.prototype.DEFAULT_KEY_LENGTH = 44;

    Identified.prototype.setKey = function(args) {
      this.keyLength = (args != null ? args.keyLength : void 0) || this.DEFAULT_KEY_LENGTH;
      return this._id = (args != null ? args.id : void 0) || randomKey(this.keyLength);
    };

    randomKey = function(keyLength) {
      var alphabet, chars, i;
      alphabet = "123456789abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ".split(/(?:)/);
      chars = (function() {
        var j, ref1, results;
        results = [];
        for (i = j = 0, ref1 = keyLength; 0 <= ref1 ? j < ref1 : j > ref1; i = 0 <= ref1 ? ++j : --j) {
          results.push(alphabet[Math.floor(Math.random() * 58)]);
        }
        return results;
      })();
      return chars.join('');
    };

    return Identified;

  })();

  module.exports = Identified;

}).call(this);
